apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-api  
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfutures-bc-beta-api
        image: gpitfuturesaksdev.azurecr.io/nhsd/buying-catalogue-api
        ports:
        - containerPort: 5100
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
        env:
        - name: CACHE_HOST
          value: ""
        - name: ASPNETCORE_ENVIRONMENT 
          value: ""
        - name: DB_NAME
          value: ""
        - name: DB_USER
          value: ""
        - name: DB_PASSWORD
          value: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-marketingpage
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-marketingpage
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-marketingpage
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfutures-bc-beta-marketingpage
        image: gpitfuturesaksdev.azurecr.io/nhsd/buying-catalogue-frontend
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-publicbrowse
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1   
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-publicbrowse
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-publicbrowse
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfutures-bc-beta-publicbrowse
        image: gpitfuturesaksdev.azurecr.io/nhsd/buying-catalogue-publicbrowse
        command: ["/bin/sh"]
        args: ["-c", "npm run start"]
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:                                
        - name: BASE_URL
          value: "http://gpitfuturesdev.uksouth.cloudapp.azure.com"
        - name: API_HOST
          value: "http://api.buyingcatalogue:5100/api/v1"
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-nginx  
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfutures-bc-beta-nginx
        image: gpitfuturesaksdev.azurecr.io/nhsd/buying-catalogue/nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m        
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-cache
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-cache  
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-cache
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfutures-bc-beta-cache
        image: index.docker.io/redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-deployment-clamav
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-clamav  
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-clamav
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfutures-bc-beta-clamav
        image: gpitfuturesaksdev.azurecr.io/nhsd/buying-catalogue/calmav
        ports:
        - containerPort: 3310
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 5100
  selector:
    app: gpitfutures-bc-app-api
---
apiVersion: v1
kind: Service
metadata:
  name: marketingpage
spec:
  ports:
  - port: 3001
  selector:
    app: gpitfutures-bc-app-marketingpage
---
apiVersion: v1
kind: Service
metadata:
  name: publicbrowse
spec:
  ports:
  - port: 3000
  selector:
    app: gpitfutures-bc-app-publicbrowse
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: gpitfutures-bc-app-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  ports:
  - port: 6379
  selector:
    app: gpitfutures-bc-app-cache
---
apiVersion: v1
kind: Service
metadata:
  name: clamav
spec:
  ports:
  - port: 3310
  selector:
    app: gpitfutures-bc-app-clamav