apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfuture-deployment-nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfuture-utility-nginx
  template:
    metadata:
      labels:
        app: gpitfuture-utility-nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-nginx
        image: gpitf/catalogue-frontend-proxy
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: bc-lb-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bc-pb-app-nginx