apiVersion: v1
kind: ReplicationController
metadata:
  name: vsts-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vsts-agent
        version: "0.1"
    spec:
      containers:
      - name: vsts-agent
        image: ubuntu:latest
        env:
          - name: VSTS_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: devpipelinevariables
                key: VSTS_ACCOUNT
          - name: VSTS_TOKEN
            valueFrom:
              secretKeyRef:
                name: devpipelinevariables
                key: VSTS_TOKEN
          - name: VSTS_POOL
            valueFrom:
              secretKeyRef:
                name: devpipelinevariables
                key: VSTS_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock