apiVersion: v1
kind: Service
metadata:
  name: {{ template "example.name" . }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.serviceTargetPort }}
  selector:
    app: {{ template "example.name" . }}-pod